title: Lehman College WiCS # your site title
author: lehmanwics
email: lehmanwics@gmail.com # email for form submission, you also have to change it in _js/scripts.js
description: > # this means to ignore newlines until "baseurl:"
  The official page and blog of the ACM-W Women in Computer Science chapter at Lehman College.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://lehmanwics.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: lcwics # replace with your_twitter_username or comment to remove link from footer
#github_username:  janczizikow # replace with your_github_username or comment to remove link from footer
instagram_username: lcwics # replace with your_instagram_username or comment to remove link from footer
social:
  name: Lehman College WiCS
  links:
    - https://twitter.com/lcwics
    - https://www.facebook.com/
    - https://www.linkedin.com/


disqus:
  shortname: lcwics # to enable comments replace with your_disqus_shortname

# Build settings
markdown: kramdown
highlighter: rouge # or pygments or null
theme: jekyll-sleek
exclude:
  - README.md
  - node_modules
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.png

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
